//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorcOzet
    {
        public int Id { get; set; }
        public int MusteriNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<double> Odenen { get; set; }
        public Nullable<double> Kalan { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> Eklenen { get; set; }
    }
}
