//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBilgi
    {
        public int FirmaId { get; set; }
        public string FirmaAd { get; set; }
        public string Telefon { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public Nullable<double> GenelBorc { get; set; }
        public Nullable<double> Odenen { get; set; }
        public Nullable<double> Kalan { get; set; }
        public string Aciklama { get; set; }
    }
}
