//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBorc
    {
        public int Id { get; set; }
        public int FirmaId { get; set; }
        public string FirmaAd { get; set; }
        public string UrunAd { get; set; }
        public string UrunGrup { get; set; }
        public string Birim { get; set; }
        public Nullable<double> Miktar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<int> BorcNo { get; set; }
        public string Aciklama { get; set; }
    }
}
